INSERT IGNORE INTO role(name) VALUES('ROLE_USER');
INSERT IGNORE INTO role(name) VALUES('ROLE_ADMIN');

INSERT IGNORE INTO team(name) VALUES('Argentina');
INSERT IGNORE INTO team(name) VALUES('Brasil');
INSERT IGNORE INTO team(name) VALUES('Uruguay');
INSERT IGNORE INTO team(name) VALUES('Chile');
INSERT IGNORE INTO team(name) VALUES('Peru');
